llm_response_generation:
  type: "openai-api"
  model: "gpt-oss-120b"
  api_url: https://llm.ai.e-infra.cz/v1/
  api_key: "xxx"
  workers: 4

dsw:
  api_url: ""
  questionnaire_uuid: ""
  token: ""

metadata:
  template_uuid: ""
  template_title: ""

logging:
  level: "INFO"

files:
  dmp_template: "jsons/he-template.json"
  config_path: "config.yaml"
  prompts_path: "prompts.yaml"
  output_markdown: "dmp_output.md"
  output_with_stats: "dmp_output_with_stats.md"
  output_pre_polish_markdown: "dmp_output_pre_polish.md"
