llm_response_generation:
  type: "openai-api"
  model: "gpt-oss-120b"
  api_url: https://llm.ai.e-infra.cz/v1/
  api_key: "xxx"
  workers: 4

dsw:
  api_url: ""

logging:
  level: "INFO"

database:
  host: "localhost"
  port: "5432"
  name: "ai_document_plugin"
  user: "ai_document_plugin"
  password: "ai_document_plugin"
  schema: "public"

files:
  config_path: "config.yaml"
  prompts_path: "prompts.yaml"
