[project]
name = "ai-document-plugin-service"
version = "0.2.2"
description = "Plugin for DSW to generate documents using AI."
keywords = ["wizard", "plugin", "ai", "document", "generation", "llm", "fastapi"]
license = "MIT"
authors = [
    { name = "Matěj Frnka", email = "matej.frnka@cvut.cz" },
    { name = "Hana Litavská", email = "hana.litavska@fit.cvut.cz" },
    { name = "Marek Suchánek", email = "marek.suchanek@ds-wizard.org" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Framework :: FastAPI",
    "License :: OSI Approved :: MIT",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.13",
    "Topic :: Internet :: WWW/HTTP",
]
requires-python = ">=3.13, <4"
dependencies = [
    "alembic",
    "httpx",
    "fastapi>=0.136.1,<1.0",
    "genson",
    "haystack-ai>=2.30.1",
    "json-repair",
    "openai",
    "pandas",
    "psycopg[binary]",
    "pyyaml",
    "sqlalchemy[asyncio]",
    "tabulate",
    "tiktoken",
    "tqdm",
]

[project.scripts]
ai-document-pipeline = "ai_document_plugin_service.run_pipeline:main"

[dependency-groups]
dev = [
    "uvicorn",
    "ruff",
    "ty",
    "pytest",
    "pytest-asyncio"
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[build-system]
requires = ["uv_build>=0.11.23,<0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "src"

[tool.ruff]
target-version = "py313"
line-length = 120
indent-width = 4
include = ["src/**/*.py"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D",
    "CPY",
    "PGH003",
    "FIX002",
    "TD002",
    "DOC201",
    "PLR0913",
    "PLR0914",
    "PLR0917",
    "COM812"
]
preview = true

[tool.ruff.lint.isort]
known-third-party = ["alembic"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
